### ISSUE TITLE
Week One

### ISSUE THREAD

**Issue by livbarton21** [ltw-webdev-6/web-app-ux#1]
This week we are aiming to finish the first 4 components of the UX portion. 

1. Target audience: Who will use your app? Be specific; Personas are encouraged
2. Website goals & value proposition: What is your app trying to do? How is it trying to do that? Why?
3. Competitive analysis: Find competitors; What do they do well? What do they do poorly?
4. Sitemap & task flows: Include all the possible screens that the app would need and how the user will access those screens

**Comment by thomasjbradley** [comment]
Thanks—but I’d like this created on your own repository. We’ll discuss the task-based Issues in class next week.
